### ISSUE TITLE
NPM Seite verlinkt nicht auf GitHub

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/iqb-components#57]

**Comment by paflov** [comment]
Was meinst du genau?

**Comment by rhenck** [comment]
https://www.npmjs.com/package/iqb-dev-components

Da ist rechts eine Verlinkung zu GitHub. Bei den Components nicht.

**Comment by paflov** [comment]
Ich hab mal den Repository-Abschnitt zur package.json hinzugefügt, dann sollte der link dann erscheinen. will jetzt nicht extra ne neue Version machen, um es zu probieren, wird man dann sehen.
